export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* サンプルCSSファイルの参照 */}
        {/* Next.jsのpublicディレクトリ配下のファイルは /css/style.css のように参照できます */}
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>{children}</body>
    </html>
  )
}
