import { Auth0Provider } from "@auth0/nextjs-auth0"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        {/* サンプルCSSファイルの参照 */}
        {/* Next.jsのpublicディレクトリ配下のファイルは /css/style.css のように参照できます */}
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        <Auth0Provider>
          {children}
        </Auth0Provider>
      </body>
    </html>
  )
}
